Retry on Permission denied
Not cool:

CiscoException: % Permission denied for the role

Assuming this is similar cause to previous auth failures. Retry on this.

Also, while we're at it, let's retry on this one, too:

CiscoException: Not connected to NETCONF server